# Konfigurasi Persistence (agar pesan tidak hilang saat restart)
persistence true
persistence_location /mosquitto/data/

# Konfigurasi Log
log_dest stdout
log_dest file /mosquitto/log/mosquitto.log

# Izinkan koneksi tanpa password (untuk tahap development/implementasi awal)
# Nanti saat di AWS VPS, ini akan kita ubah menjadi false dan menggunakan password
allow_anonymous true

# ==========================================
# Listener 1: MQTT Standar (Port 1883)
# Digunakan oleh: dummy_sensor.py, ESP32, dan Backend Laravel
# ==========================================
listener 1883 0.0.0.0

# ==========================================
# Listener 2: WebSockets (Port 9001)
# Digunakan oleh: Frontend Dashboard (Next.js/React) agar bisa subscribe real-time
# ==========================================
listener 9001 0.0.0.0
protocol websockets
