version: '3.8'

services:
  backend:
    build: .
    container_name: laravel_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./:/app   # 🔥 biar .env sync & code update realtime
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: next_app
    ports:
      - "3000:3000"
    restart: unless-stopped

  mediamtx:
    image: bluenviron/mediamtx
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
    ports:
      - "8554:8554"
      - "8888:8888"
      - "8889:8889"

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ews
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ews_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/dump:/docker-entrypoint-initdb.d
    restart: unless-stopped

  kong:
    image: kong:latest
    container_name: kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
    volumes:
      - ./kong.yml:/kong/kong.yml
    ports:
      - "8080:8000"   # public access
      - "8001:8001"   # admin API
    restart: unless-stopped

volumes:
  db_data:
